export const categories = [
  {
    id: 1,
    name: 'Web Dev',
    slug: 'web-dev',
    published: '24/05/2023',
    author: 'Joel Onwuanaku',
  },
  {
    id: 2,
    name: 'Mobile App Dev',
    slug: 'mobile-app-dev',
    published: '18/08/2022',
    author: 'Alice Johnson',
  },
  {
    id: 3,
    name: 'Data Science',
    slug: 'data-science',
    published: '10/03/2023',
    author: 'Michael Smith',
  },
  {
    id: 4,
    name: 'UI/UX Design',
    slug: 'ui-ux-design',
    published: '30/06/2022',
    author: 'Emily Davis',
  },
  {
    id: 5,
    name: 'Game Development',
    slug: 'game-development',
    published: '05/12/2022',
    author: 'David Brown',
  },
  {
    id: 6,
    name: 'Machine Learning',
    slug: 'machine-learning',
    published: '14/01/2023',
    author: 'Sophia Wilson',
  },
  {
    id: 7,
    name: 'Frontend Frameworks',
    slug: 'frontend-frameworks',
    published: '22/09/2022',
    author: 'Liam Miller',
  },
  {
    id: 8,
    name: 'Backend Development',
    slug: 'backend-development',
    published: '07/04/2023',
    author: 'Olivia Harris',
  },
  {
    id: 9,
    name: 'Cybersecurity',
    slug: 'cybersecurity',
    published: '03/11/2022',
    author: 'Ethan White',
  },
  {
    id: 10,
    name: 'Cloud Computing',
    slug: 'cloud-computing',
    published: '19/07/2022',
    author: 'Ava Jackson',
  },
];
