export const images = [
  {
    id: 1,
    src: 'https://placehold.co/600x400',
    caption: 'Sail Away to Serenity',
    description: 'A serene day on the water with colorful boats, inviting you to sail away to serenity.',
    slug: 'sail-away-to-serenity',
  },
  {
    id: 2,
    src: 'https://placehold.co/600x400',
    caption: 'Vibrant Color Pencils Symphony',
    description: 'A symphony of vibrant color pencils creating an artistic masterpiece.',
    slug: 'vibrant-color-pencils-symphony',
  },
  {
    id: 3,
    src: 'https://placehold.co/600x400',
    caption: 'Bountiful Red Apple Harvest',
    description: 'A bountiful harvest of red apples and other delectable red fruits.',
    slug: 'bountiful-red-apple-harvest',
  },
  {
    id: 4,
    src: 'https://placehold.co/600x400',
    caption: 'Geometric Patterns in Monochrome',
    description: 'Abstract and geometric patterns in captivating black and white.',
    slug: 'geometric-patterns-in-monochrome',
  },
  {
    id: 5,
    src: 'https://placehold.co/600x400',
    caption: 'Mysteries of the Number Eight',
    description: 'Unlock the mysteries of the intriguing and mysterious number eight formation.',
    slug: 'mysteries-of-the-number-eight',
  },
  {
    id: 6,
    src: 'https://placehold.co/600x400',
    caption: 'Chaotic Creativity Unleashed',
    description: 'Creative chaos with mesmerizing designs formed by numbers and shapes.',
    slug: 'chaotic-creativity-unleashed',
  },
  {
    id: 7,
    src: 'https://placehold.co/600x400',
    caption: 'Intriguing Three-Fold Harmony',
    description: 'Intriguing patterns and lines forming a captivating harmony with the number three.',
    slug: 'intriguing-three-fold-harmony',
  },
  {
    id: 8,
    src: 'https://placehold.co/600x400',
    caption: 'Artistic Fusion of Two and One',
    description: 'An artistic fusion featuring the numbers two and one, forming a captivating composition.',
    slug: 'artistic-fusion-of-two-and-one',
  },
  {
    id: 9,
    src: 'https://placehold.co/600x400',
    caption: 'Vibrant Flower Interior Close-Up',
    description: 'A mesmerizing close-up of a vibrant and breathtaking flower interior.',
    slug: 'vibrant-flower-interior-close-up',
  },
  {
    id: 10,
    src: 'https://placehold.co/600x400',
    caption: 'Rustic Charm of an Old Barn',
    description: 'The rustic charm and timeless beauty of an old and weathered barn in the countryside.',
    slug: 'rustic-charm-of-an-old-barn',
  },
  {
    id: 11,
    src: 'https://placehold.co/600x400',
    caption: 'The Zest of an Orange Macro',
    description: 'Experience the zest and intricate details of a vibrant and juicy orange fruit up close.',
    slug: 'the-zest-of-an-orange-macro',
  },
];
