export const projects = [
  {
    id: 1,
    project: 'Web Development Portfolio',
    published: '2023-09-01',
    author: 'John Doe',
    slug: 'web-development-portfolio',
  },
  {
    id: 2,
    project: 'E-commerce Website Redesign',
    published: '2023-08-15',
    author: 'Jane Smith',
    slug: 'ecommerce-website-redesign',
  },
  {
    id: 3,
    project: 'Mobile App for Task Management',
    published: '2023-07-20',
    author: 'David Johnson',
    slug: 'mobile-app-for-task-management',
  },
  {
    id: 4,
    project: 'Data Analytics Dashboard',
    published: '2023-06-10',
    author: 'Emily Davis',
    slug: 'data-analytics-dashboard',
  },
  {
    id: 5,
    project: 'Game Development Showcase',
    published: '2023-05-05',
    author: 'Michael Wilson',
    slug: 'game-development-showcase',
  },
  {
    id: 6,
    project: 'Machine Learning Research',
    published: '2023-04-15',
    author: 'Sophia Martinez',
    slug: 'machine-learning-research',
  },
  {
    id: 7,
    project: 'UI/UX Design Prototypes',
    published: '2023-03-20',
    author: 'Daniel Brown',
    slug: 'ui-ux-design-prototypes',
  },
  {
    id: 8,
    project: 'Backend System Optimization',
    published: '2023-02-12',
    author: 'Olivia White',
    slug: 'backend-system-optimization',
  },
  {
    id: 9,
    project: 'Cybersecurity Best Practices',
    published: '2023-01-08',
    author: 'Ethan Turner',
    slug: 'cybersecurity-best-practices',
  },
  {
    id: 10,
    project: 'Cloud Computing Solutions',
    published: '2022-12-01',
    author: 'Ava Jackson',
    slug: 'cloud-computing-solutions',
  },
  // Add more entries as needed
];
