export const reviews = [
  {
    id: 1,
    name: 'Product A',
    review: 'This product exceeded my expectations! It works flawlessly and is very user-friendly.',
    rating: 5,
    author: 'John Doe',
    published: '2023-09-15',
    slug: 'product-a-review',
  },
  {
    id: 2,
    name: 'Service B',
    review: 'I had a great experience with their service. The support team was very helpful.',
    rating: 4,
    author: 'Jane Smith',
    published: '2023-09-12',
    slug: 'service-b-review',
  },
  {
    id: 3,
    name: 'Book C',
    review: `This book is a must-read for anyone interested in the topic. It's well-written and informative.`,
    rating: 5,
    author: 'David Johnson',
    published: '2023-09-10',
    slug: 'book-c-review',
  },
  {
    id: 4,
    name: 'Movie D',
    review: 'I enjoyed this movie a lot. The storyline and acting were top-notch.',
    rating: 4,
    author: 'Emily Davis',
    published: '2023-09-08',
    slug: 'movie-d-review',
  },
  {
    id: 5,
    name: 'Restaurant E',
    review: 'The food at this restaurant was delicious, and the ambiance was fantastic. Highly recommended!',
    rating: 5,
    author: 'Michael Wilson',
    published: '2023-09-05',
    slug: 'restaurant-e-review',
  },
  {
    id: 6,
    name: 'Product F',
    review: "I purchased this product, and it turned out to be a disappointment. It didn't work as expected.",
    rating: 2,
    author: 'Sophia Martinez',
    published: '2023-09-03',
    slug: 'product-f-review',
  },
  {
    id: 7,
    name: 'Book G',
    review: "This book was a letdown. It lacked depth and didn't live up to the hype.",
    rating: 2,
    author: 'Daniel Brown',
    published: '2023-09-01',
    slug: 'book-g-review',
  },
  {
    id: 8,
    name: 'Service H',
    review: 'I had a terrible experience with their service. Avoid it at all costs!',
    rating: 1,
    author: 'Olivia White',
    published: '2023-08-30',
    slug: 'service-h-review',
  },
  {
    id: 9,
    name: 'Movie I',
    review: 'I found this movie boring and poorly made. Not worth watching.',
    rating: 1,
    author: 'Ethan Turner',
    published: '2023-08-28',
    slug: 'movie-i-review',
  },
  {
    id: 10,
    name: 'Restaurant J',
    review: 'I had a bad experience at this restaurant. The food was cold, and the service was slow.',
    rating: 2,
    author: 'Ava Jackson',
    published: '2023-08-25',
    slug: 'restaurant-j-review',
  },
  // Add more entries as needed
];
