export const tags = [
  {
    id: 1,
    name: 'Web Dev',
    published: '24/05/2023',
    author: 'Joel Onwuanaku',
    slug: 'web-dev',
  },
  {
    id: 2,
    name: 'Data Science',
    published: '18/08/2022',
    author: 'Alice Johnson',
    slug: 'data-science',
  },
  {
    id: 3,
    name: 'Mobile App Dev',
    published: '06/11/2022',
    author: 'Michael Smith',
    slug: 'mobile-app-dev',
  },
  {
    id: 4,
    name: 'UI/UX Design',
    published: '17/03/2023',
    author: 'Emily Davis',
    slug: 'ui-ux-design',
  },
  {
    id: 5,
    name: 'Game Development',
    published: '09/05/2022',
    author: 'David Brown',
    slug: 'game-development',
  },
  {
    id: 6,
    name: 'Machine Learning',
    published: '04/01/2023',
    author: 'Sophia Wilson',
    slug: 'machine-learning',
  },
  {
    id: 7,
    name: 'Frontend Frameworks',
    published: '19/08/2022',
    author: 'Liam Miller',
    slug: 'frontend-frameworks',
  },
  {
    id: 8,
    name: 'Backend Development',
    published: '02/12/2022',
    author: 'Olivia Harris',
    slug: 'backend-development',
  },
  {
    id: 9,
    name: 'Cybersecurity',
    published: '14/04/2023',
    author: 'Ethan White',
    slug: 'cybersecurity',
  },
  {
    id: 10,
    name: 'Cloud Computing',
    published: '30/10/2022',
    author: 'Ava Jackson',
    slug: 'cloud-computing',
  },
  // Add more entries as needed
];
